---
resources:
  - name: app
    type: git
    source:
      uri: https://github.com/agentreno/concourse-example.git
      branch: master

jobs:
  - name: unit-tests
    public: true
    plan:
      - get: app
        trigger: true
      - task: unit-tests
        file: app/concourse-full-split/unit-tests/unit-tests.yml

  - name: build-and-push
    public: true
    plan:
      - get: app
        passed:
          - unit-tests
        trigger: true
      - task: build
        file: app/concourse-full-split/build/build.yml
