---
resources:
  - name: app
    type: git
    source:
      uri: https://github.com/agentreno/concourse-example.git
      branch: master

jobs:
  - name: unit-tests
    public: true
    plan:
      - get: app
        trigger: true
      - task: run-pytest
        config:
          inputs:
            - name: app
          platform: linux
          image_resource:
            type: registry-image
            source: {repository: python, tag: 3.9}
          run:
            dir: app
            file: concourse/unit-tests.sh
